export const chatData = {
  storageKey: "smmkadr_chat_history",
  profileKey: "smmkadr_chat_profile",
  leadKeywords: [
    "хочу",
    "интересно",
    "заказать",
    "связаться",
    "заявка",
    "заинтересован",
    "сотрудничество",
    "предложение",
    "напишите",
  ],
  quickActions: [
    { id: "price", labelKey: "chat_action_prices", query: "цена" },
    { id: "services", labelKey: "chat_action_services", query: "услуги" },
    { id: "request", labelKey: "chat_action_request", query: "оставить заявку" },
    { id: "manager", labelKey: "chat_action_manager", query: "связаться с менеджером" },
    { id: "instagram", labelKey: "chat_action_instagram", query: "instagram" },
    { id: "packages", labelKey: "chat_action_packages", query: "пакеты" },
  ],
  ctaActions: [
    {
      id: "apply",
      labelKey: "chat_cta_apply",
      type: "route",
      route: "/contacts",
    },
    {
      id: "whatsapp",
      labelKey: "chat_cta_whatsapp",
      type: "url",
      url: "https://wa.me/996700000000",
    },
    {
      id: "telegram",
      labelKey: "chat_cta_telegram",
      type: "url",
      url: "https://t.me/smmkadr",
    },
    {
      id: "cases",
      labelKey: "chat_cta_cases",
      type: "url",
      url: "https://www.instagram.com/",
    },
  ],
  serviceMatchers: {
    Таргет: ["таргет", "target", "реклама", "аудиторию"],
    Instagram: ["instagram", "инстаграм", "insta"],
    TikTok: ["tiktok", "тик-ток", "тик ток", "tiktok"],
    Reels: ["reels", "рилс", "рилсами", "reels"],
    Мобилография: ["мобилограф", "мобилография", "съёмка на телефон", "vertical"],
    Дизайн: ["дизайн", "графика", "графический", "брендбук"],
    Отзывы: ["отзывы", "кейсы", "результаты", "кейсы"],
  },
  packageMatchers: {
    Standard: ["standard", "стандарт", "standard"],
    Advanced: ["advanced", "расширенный", "advanced"],
    Basic: ["basic", "базовый", "разовый", "basic"],
    Pro: ["pro", "продвинутый", "pro"],
  },
};
